### ISSUE TITLE
演算子: コードの統一のため以下のエイリアスは使用しないこと(and, or, is, isnt)

### ISSUE THREAD

**Issue by khirayama** [khirayama/styleguide#1]
項目: [演算子](https://github.com/khirayama/styleguide/blob/master/coffeesctipt.md#演算子)にて
可読性やレビュー基準として、`&&, ||, ==, !=`と`and, or, is, isnt`のどちらかに統一したほうがよいのではないかと考えています。
今のところ、感覚的に`&&, ||, ==, !=`で進めていますが、双方のメリット、デメリット。そもそも統一の必要性などあれば意見伺いたいです。

**Comment by khirayama** [comment]
@syguer

> 理由: `==`でいいと思う。`is`にすると否定が`not`じゃないとあれで。でもrubyでは`not`無しになってたりという理由で混乱するので

**Comment by nyangry** [comment]
`is` シンタックス肯定派
- JSの `!=` と `!==` の違いを意識せずに混在されると気持ち悪い
- 自然言語的で直感的に読める

パッと思い浮かぶメリット

**Comment by khirayama** [comment]
[口頭] 
これはいろんなケースを考えると &&, ||, ==, !=を推奨。とはいえ、and, or, is, isntも禁止しない。 ※ レビューで指摘が入る場合はありえます（例： if isnt AAA is BBB or CCC など）
