### ISSUE TITLE
camelCase vs. under_scores

### ISSUE THREAD

**Issue by nyangry** [khirayama/styleguide#10]
> いや〜〜〜変数名はマジでキャメルケース読みづらいなーと感じるので苦痛を感じてしまいますが、
> 大勢が統一すべきであればそちらに合わせます :bow:

とはいったものの、これってJSON返す側がスネークケースの場合どうすれば良いのでしょうか？

**Comment by khirayama** [comment]
まじこれです。笑  
個人的には`hoge['snake_case']`とかで文字列として扱うことで、変数名とは区別するように心がけてます。（でもLinterでhoge.snake_caseでアクセスしろよ！って引っかかっちゃうw）  

camelCase
- JSのメソッドを統一できる  
- JS周りはcamelCaseが多い
- 統一性という意味ではAPIのキーがsnake_caseなのが気になる

snake_case
- camelCaseより見やすい
- Rubyぽい
- JSメソッドがcamelCaseなので、混在が避けれない

あたりでしょうか...？

FYI https://github.com/jashkenas/coffeescript/issues/425

**Comment by nyangry** [comment]
ｆｍｆｍ！コメントありがとうございます！

ちなみにJSで変数とメソッドの違いはあまり意識しなくても良い感じでしょうか？

例えば読みやすいからスネークケースに全て統一したいというわけではなく、
メソッドは今もキャメルで書いていて、変数名がスネークケースなのですが、

```
＿人人人人人人人人人人人人人人＿
＞　全てがオブジェクト　＜
￣ＹＹＹＹＹＹＹＹＹＹＹＹＹＹ￣
```

だからメソッド、変数の違いは気にするな！という方が正しい？

**Comment by khirayama** [comment]
www

こちらこそありがとうございますです！
正直、そこ考えてなかったですねw
気にしないでいただきたい方向ですwww

**Comment by khirayama** [comment]
[口頭] camelCaseで仮キメで推進。難しければ、再考。
