### ISSUE TITLE
jqueryのイベントに対するハンドラと暗黙のリターン

### ISSUE THREAD

**Issue by OsugaHiroshi** [khirayama/styleguide#16]
### コールバックとして指定する関数/メソッドの返り値は明示する。(= 暗黙のリターンを使わない。

意図せず false を返すとイベントが止まってしまい、全体を破壊しかねない

問題だと思っているコードはこういうもの

``` coffee
$xxx.on 'click', (event) ->
    updateModal(false) # clickイベントが止まる

updateModal = ( state ) ->
    @state = state
```

なので以下のようにする。

``` coffee
$xxx.on 'click', (event) ->
    updateModal(false) # clickイベントが止まる
    return true #undefinedとかでもいい

updateModal = ( state ) ->
    @state = state
```

**Comment by OsugaHiroshi** [comment]
守るのも守らせるのも辛いので、規約にどうしても入れたいというほどではないです。
議論済みにしておくことが重要かなと思いましたマル

**Comment by kjirou** [comment]
仰るとおりなんですが、守るのが辛いですね・・・これは辛い・・・。

**Comment by khirayama** [comment]
なるほど。もっともすぎる。
とはいえ、規約とした場合、守ろうとするわけで、とはいえ、なかなか辛そうな。。。
規約というよりは知見という風に感じ取れるのですが、どうでしょうか。

**Comment by OsugaHiroshi** [comment]
結論: 規約ではない

いいと思います！
