### ISSUE TITLE
関数: メソッド呼び出しの括弧は省略しないこと

### ISSUE THREAD

**Issue by khirayama** [khirayama/styleguide#8]
項目: [関数](https://github.com/khirayama/styleguide/blob/master/coffeesctipt.md#関数)
@syguer
メソッド呼び出しについて意見いただいたので。

> ここ括弧入れると数行下で閉じ括弧かかなきゃいけなくなって、coffeeのインデントでステートメント区切るっていうのに合わない気もしつつ

```
# 括弧あり
$('.className').on('click', ->
  some.action()
)

# 括弧なし
$('.className').on 'click', ->
  some.action()

```

**Comment by khirayama** [comment]
今上がってるのは3パターン
1. 括弧あり
2. 括弧なし
3. 基本的に括弧あり、複数行の場合は括弧なし

```
# 1. 括弧あり
$hoge = $('.js-hoge')

$('.className').on('click', ->
  some.action()
)

# 2. 括弧なし
$hoge = $ '.js-hoge'

$('.className').on 'click', ->
  some.action()


# 3. 基本的に括弧あり、複数行の場合は括弧なし
$hoge = $('.js-hoge')

$('.className').on 'click', ->
  some.action()
```

個人的には3が良さそうだけど、Linterとかどうなのかな？

**Comment by khirayama** [comment]
CoffeeLintの場合、3のオプションはないためLinterでのチェックは難しい模様

**Comment by khirayama** [comment]
CoffeeLintでもno_implicit_parensのstrictをfalseで行けたので、3案採用。  
正確には複数行の場合の括弧は省略してもエラーがでない状態。括弧がある場合でもエラーがでませんので、ご留意ください。

**Comment by syguer** [comment]
:+1:

**Comment by takuyan** [comment]
:+1:
